### ISSUE TITLE
Timer patch Done output should default to 1 (true)

### ISSUE THREAD

**Issue by individual11** [facebook/origami#21]
When using the Timer patch, the Done output does not default to true (that the timer is done). Instead, it has to run once in order for it to be done. What I have to do now is set a conditional patch and use the Time output on the Timer patch as the first value, and set the condition to be _equal to_ 0.

**Comment by tarngerine** [comment]
This is intentional. A timer isn't done until it finishes.

Also super old task. Sorry! Doing some housecleaning
