### ISSUE TITLE
Mouse drag drifting issue

### ISSUE THREAD

**Issue by trive** [facebook/origami#22]
I have noticed a dragging “drift” for elements rendered inside a Phone patch.

Download this patch and try to drag the circle—you'll see that the mouse position and the circle drift away.
https://dl.dropboxusercontent.com/u/369957/static/DragDrift.qtz

Is this a bug?

**Comment by tarngerine** [comment]
Hey all, this seems super old (sorry, housecleaning) and as noted above it's not quite worth fixing this since our primary concerns are with supporting prototyping with origami Layers rather than QC unit based consumer patches.

**Comment by trive** [comment]
Makes sense.
Happy Holidays :)
