### ISSUE TITLE
New button to stop/start in one action

### ISSUE THREAD

**Issue by adamselby** [facebook/origami#28]
In the Viewer, it'd be really great if we could restart it with one button, rather than hitting both Stop/Start.

**Comment by bryanmanio** [comment]
+1

**Comment by tarngerine** [comment]
Thanks for the recommendation. We haven't decided to prioritze this (obviously, commenting after more than 1.5 years), but for now I'd recommend using the shortcuts CMD + . and CMD + R — it's one more key press but basically just as fast. Sorry!
