### ISSUE TITLE
Iterations count editor crash

### ISSUE THREAD

**Issue by jonathanhammond** [facebook/origami#36]
Summary:
Changing the iteration count with a velocity patch within causes a QC editor crash.
This is due to a QC feedback patch bug that is used in the velocity patch. 

Steps to Reproduce:
1. Place a velocity patch within an iterator hook up to a renderer patch
2. Change the iterator count

Expected Results:
No crash

Actual Results:
QC editor crash, and possible memory leak.

Solution
Within the velocity patch use a queue patch to determine velocity instead of a feedback patch see attachment section.

Version:
Origami 1.2
QC editor Version 4.6 (151)
Framework Version 5.1 (319)

Attachments:
https://www.dropbox.com/s/r9e7oh9u65bedzm/Velocity.zip
ReproduceVelocityCrash.qtz
Demonstrates QC editor crash

velocityDifferenceTest.qtz 
Demonstrates that there is no accountable difference between velocity results.

Velocity.qtz
Proposed replacement for the current Origami velocity patch.

**Comment by justaddmusic** [comment]
This one is still driving me crazy! Can we get it fixed.

**Comment by jonathanhammond** [comment]
Better late than never ;) Last Value Engine, thanks you
