### ISSUE TITLE
Interaction 2 not recognising a masked image

### ISSUE THREAD

**Issue by jonathanhammond** [facebook/origami#38]
Summary:
The interaction 2 patch hit area is not correct when using a masked Layer.

Steps to Reproduce:
See dropbox link https://dl.dropboxusercontent.com/u/31564678/OrigamiExamples/maskLayerBug.qtz

Expected Results:
Regarding example composition, no interaction when outside the circle (mask image). See the hitTest patch with mask in Quartz Composer

Actual Results:
Interaction when inside the layer patch before masked

Solution
look into the hitTest patch, some Facebook magic to the interaction 2 patch

Version:
Origami 1.2 +
QC editor Version 4.6 (151.1)
Framework Version 5.1 (319)

Attachments:
https://dl.dropboxusercontent.com/u/31564678/OrigamiExamples/maskLayerBug.qtz

**Comment by tarngerine** [comment]
Unfortunately we have no plans to support Interaction masked to a circle. For most prototyping/user testing purposes it doesn't detract from the prototype, so it's a low priority for us/expensive for QC to calculate hit area based on an arbitrary alpha mask.

**Comment by jonathanhammond** [comment]
Ok, was really needed in some rial examples of mine last year, but I can understand this might be hard to implement.

**Comment by tarngerine** [comment]
It would be super cool - totally agree :) if we think of a good inexpensive way to do it itd be cool

Sent from Outlook Mobile




On Fri, Dec 25, 2015 at 11:49 AM -0800, "Jonathan Hammond" <notifications@github.com> wrote:












Ok, was really needed in some rial examples of mine last year, but I can understand this might be hard to implement.
