### ISSUE TITLE
Code export not working for me 

### ISSUE THREAD

**Issue by jwebcat** [facebook/origami#45]
When I export a project all I get are the utility functions. 

Am I missing something? 

Any help is appreciated. 

Thanks for this great tool, it is fantastic.!

**Comment by alexeichemenda** [comment]
Same here. For the "Swipe Card" example, I only have 1 file generated, and here's its content :
#import "ViewController.h"
#import <POP/POP.h>
#import <POP/POPLayerExtras.h>

@interface ViewController ()
@end

@implementation ViewController

// Utilities

**Comment by devSC** [comment]
me too,please tell how should to do... Thanks a lot.

**Comment by ichu501** [comment]
me too have the same problem.

**Comment by lilymdwyer** [comment]
I'm also having the same issue with this! I'm exporting Android code and there are only blank functions.

**Comment by jwebcat** [comment]
For all to know I heard the update that will allow origami to export usable code is coming soon

**Comment by jwebcat** [comment]
I talked with some of the folks in the rebound js Facebook group. I have asked this same question there and I am awaiting a response.

**Comment by jwebcat** [comment]
You have to connect them to a pop animation patch. Currently pop animation
patches are the only ones that can be exported. Support for the other
patches is supposed to be on its way eventually.

**Comment by pcqpcq** [comment]
it works for me, with origami 2.0.2. @jwebcat was right

**Comment by mRs-** [comment]
same problem with the classic animation

**Comment by Daemon-Devarshi** [comment]
I followed this video tutorial step by step: [Introduction to Origami Video](https://vimeo.com/120349147)  and then selected Code Export -> iOS but it did not generate any file :( When I downloaded the attached prototype from this link: [Introduction to Origami.zip](https://www.dropbox.com/s/xcmzr6sefn13abf/Introduction%20to%20Origami.zip?dl=0) it generated the respective viewController, any ideas?

**Comment by tarngerine** [comment]
Hi all, as noted on the Code Export docs (and from jwebcat above) we only support a few things in Code Export right now:

- Pop Animation patches
- Transitions connected to Pop animation patches
- The connections between those Transitions and Layers

http://facebook.github.io/origami/documentation/concepts/CodeExport.html

Daemon-Devarshi, hard to answer without seeing your composition. Can you open a new issue if you are still experiencing the issue?
