### ISSUE TITLE
Browser Chrome – Is it possible to add custom window chrome?

### ISSUE THREAD

**Issue by berndpl** [facebook/origami#47]
In the Origami package I could identify `FBSafariToolbarController.nib`. is it possible to replace this or add an additional version of the toolbar shown in the Quartz viewer when adding the the *Browser Chrome* patch?

**Comment by tarngerine** [comment]
Hi, unfortunately we do not support custom versions in our API for replacing the window chrome. It's possible to do on your own (as we did) but we cannot show you how in this context.
