### ISSUE TITLE
Documentation - Shortcut duplicates

### ISSUE THREAD

**Issue by makeshowlearn** [facebook/origami#48]
Switch, pulse, and delay are listed twice:
![image](https://cloud.githubusercontent.com/assets/10263341/6433253/0e33e0e0-c038-11e4-8c24-5d4d0c23eac0.png)

**Comment by tylerhowarth** [comment]
This has been addressed in this commit - https://github.com/facebook/origami/commit/9dfa8afdb2dcb932664744b9cd454324388579f9

**Comment by tylerhowarth** [comment]
![image](https://cloud.githubusercontent.com/assets/56019/6511431/bc2c6334-c321-11e4-8ffe-be244b9988e6.png)
