### ISSUE TITLE
Origami Plugin is broken on OS X El Capitan

### ISSUE THREAD

**Issue by philipamour** [facebook/origami#50]
Quartz Composer freezes when trying to open or create a new document that includes Phone Origami patch.

This is the error I get when trying to run the Phone patch in viewer:

0x8b5a34b4: -[QCContext nextExecutionTimeForPatch:time:arguments:]
0x8b5a3169: -[QCGraphicsContext nextExecutionTimeForPatch:time:arguments:]
0x8b5a2f64: -[QCOpenGLContext nextExecutionTimeForPatch:time:arguments:]
0x8b65f182: -[QCView nextExecutionTime:arguments:]
0x0e5f0101
0x8b65f3c6: -[QCView render:arguments:]
0x8b65ff06: -[QCView startRendering:]
0x0e5ef987
0x14af01a1: -[FBOrigamiAdditions(Retina) startRendering:]
0x8705aeaf: ___CFXRegistrationPost_block_invoke
0x8705a571: _CFXRegistrationPost
0x8705a2f2: ___CFXNotificationPost_block_invoke
0x870576c2: -[_CFXNotificationRegistrar find:object:observer:enumerator:]
0x86f456ec: _CFXNotificationPost
0x8fc3d698: -[NSNotificationCenter postNotificationName:object:userInfo:]
0x862c496a: -[NSWindow _reallyDoOrderWindow:relativeTo:findKey:forCounter:force:isModal:]
0x86999e33: __71-[NSWindow _doOrderWindow:relativeTo:findKey:forCounter:force:isModal:]_block_invoke3296
0x869d034b: NSPerformVisuallyAtomicChange
0x862c3dbd: -[NSWindow _doOrderWindow:relativeTo:findKey:forCounter:force:isModal:]
0x862c396e: -[NSWindow orderWindow:relativeTo:]
0x862bb0f5: -[NSWindow makeKeyAndOrderFront:]
0x8e5e0919: -[QLSeamlessDocumentOpener showWindow:contentFrame:withBlock:]
0x86352f2c: -[NSWindowController showWindow:]
0x0e5ef488
0x0e5f0f14
0x864ec6ad: -[NSToolbarButton sendAction:to:]
0x863e79ac: -[NSToolbarItemViewer mouseDown:]
0x86993cee: -[NSWindow _handleMouseDownEvent:isDelayedEvent:]
0x86994fad: -[NSWindow _reallySendEvent:isDelayedEvent:]
0x862ee356: -[NSWindow sendEvent:]
0x862ea9cf: -[NSApplication sendEvent:]
0x0e5e67ff
0x86217309: -[NSApplication run]
0x0e5e3ebc

**Comment by bwalkin** [comment]
Just fixed this in our internal patch. We'll ship the fix in the next release. You can fix it locally by going into the Phone patch, searching for "Disc Blur" and replacing it with a Gaussian Blur patch.

**Comment by winzig** [comment]
Was this ever fixed in the shipping release? If not, can you elaborate on the workaround? I'm on El Capitan beta 5, Quartz Composer 4.6.1, and Origami 2.0.2, and I cannot load any examples that I've downloaded.

**Comment by yuppielabel** [comment]
Its still an issue in El Cap beta 8.
