### ISSUE TITLE
Dead Link to Quartz Composer in the docs

### ISSUE THREAD

**Issue by iandundas** [facebook/origami#51]
http://facebook.github.io/origami/download/ -> the link to Quartz Composer no longer works. I can't actually locate a working link either :/

**Comment by jonathanhammond** [comment]
Until this gets fixed. Either open Xcode, on the title bar select Xcode > Open Developer Tools > More Developer Tools...

Or go directly to

https://developer.apple.com/downloads/

The direct link to the latest graphic tools which contains Quartz Composer is here
http://adcdownload.apple.com/Developer_Tools/Graphics_Tools_for_Xcode_6.3/GraphicsTools_Xcode_6.3.dmg

**Comment by iandundas** [comment]
Hmm, something's up with Apple (at my end at least)

That direct link gives me this: <image src="http://f.cl.ly/items/360z3j2C1F1B1U380T2C/Image%202015-06-11%20at%205.51.48%20pm.png" />

and Quartz Composer isn't listed as a download here https://developer.apple.com/downloads/?name=quartz

Oh well, teething problems I guess.

**Comment by bwalkin** [comment]
They changed something so direct links no longer work. Trying to figure out a better solution.

**Comment by neutyp** [comment]
I'm guessing that re-hosting that `GraphicsTools_Xcode_6.3.dmg` would be against their terms of use?

**Comment by arbales** [comment]
That'd be nice, Tim, but we can't redistribute third party software without their explicit written permission.

**Comment by tarngerine** [comment]
I think the best solution we have for now is just prefilling with the search query for Graphics Tools. Unfortunately this gets wiped if you need to log in. Apple...
