### ISSUE TITLE
Browser Chrome example?

### ISSUE THREAD

**Issue by neezer** [facebook/origami#53]
The website says that you can you Origami to prototype websites in browser windows (for consumption on desktop computers, not mobile), yet none of the examples detail how to do this. Playing around with it some I couldn't figure out how to pipe the image output into the browser chrome patch.

Could someone just leave a quick example of how to get started with this? Thanks!

**Comment by drewhamlin** [comment]
Hi neezer, I highly recommend the Origami Community (https://www.facebook.com/groups/origami.community/) for questions of this nature in the future.

The Browser Chrome patch simply morphs the viewer window to have the appearance of a browser window. You can read more about this in its Patch Library window description. To draw an image on the screen (and in this case, in the browser window), just use a Layer patch the way you normally would.
