### ISSUE TITLE
Git repo is falling behind official releases

### ISSUE THREAD

**Issue by neutyp** [facebook/origami#54]
The official release version is now at `2.0.2`, but the repo hasn't been updated since `1.4` — will you update the repo for others interested in contributing to improving patches, etc? 

Also, my understand is that what's being shared here is the compiled form of Origami. Would it be possible to share the Xcode project or whatever appropriate source code?

**Comment by robincwillis** [comment]
:+1:

**Comment by tarngerine** [comment]
Updated to 2.1.2 public release

Unfortunately we cannot share the source code due to its heavy use of private APIs.
