### ISSUE TITLE
Quartz Composer stuck on EL Capitan Xcode7.0 beta4

### ISSUE THREAD

**Issue by ZZHHAANNGG** [facebook/origami#55]
*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]

![screen shot 2015-08-18 at 9 07 36 pm]
(https://cloud.githubusercontent.com/assets/12008247/9348526/2e2d3ffa-45ed-11e5-9df1-469313b64207.png)

0x87575ffa: -[QCContext nextExecutionTimeForPatch:time:arguments:]
0x87575cb5: -[QCGraphicsContext nextExecutionTimeForPatch:time:arguments:]
0x87575abb: -[QCOpenGLContext nextExecutionTimeForPatch:time:arguments:]
0x87631718: -[QCView nextExecutionTime:arguments:]
0x0806f101
0x8763195c: -[QCView render:arguments:]
0x8763249c: -[QCView startRendering:]
0x0806e987
0x0ba1a1a1: -[FBOrigamiAdditions(Retina) startRendering:]
0x9795454f: ___CFXRegistrationPost_block_invoke
0x97953c17: _CFXRegistrationPost
0x97953982: ___CFXNotificationPost_block_invoke
0x9794d842: -[_CFXNotificationRegistrar find:object:observer:enumerator:]
0x9783c9a5: _CFXNotificationPost
0x97064133: -[NSNotificationCenter postNotificationName:object:userInfo:]
0x94004f6f: -[NSWindow _reallyDoOrderWindow:relativeTo:findKey:forCounter:force:isModal:]
0x946d011f: __71-[NSWindow _doOrderWindow:relativeTo:findKey:forCounter:force:isModal:]_block_invoke3337
0x947075a1: NSPerformVisuallyAtomicChange
0x940043d0: -[NSWindow _doOrderWindow:relativeTo:findKey:forCounter:force:isModal:]
0x94003f7b: -[NSWindow orderWindow:relativeTo:]
0x93ffb8b2: -[NSWindow makeKeyAndOrderFront:]
0x8e19f1fe: -[QLSeamlessDocumentOpener showWindow:contentFrame:withBlock:]
0x9408e184: -[NSWindowController showWindow:]
0x0806e488
0x940a5412: -[NSDocument showWindows]
0x944435ff: __90-[NSDocumentController(NSInternal) _autoreopenDocumentsFromRecords:withCompletionHandler:]_block_invoke1897
0x9443b351: __89-[NSDocumentController reopenDocumentForURL:withContentsOfURL:display:completionHandler:]_block_invoke_2
0x978aace4: __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__
0x9789c9a5: __CFRunLoopDoBlocks
0x9789c70b: __CFRunLoopRun
0x9789bb78: CFRunLoopRunSpecific
0x895bf3e5: RunCurrentEventLoopInMode
0x895bf083: ReceiveNextEventCommon
0x895befbb: _BlockUntilNextEventMatchingListInModeWithFilter
0x93f65ae7: _DPSNextEvent
0x94331ac5: -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
0x93f5b986: -[NSApplication run]
0x08062ebc

**Comment by tarngerine** [comment]
Hi, are you still encountering this? We've fixe a few El Capitan issues since it was in beta August.
