### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by suewonjp** [facebook/origami#56]
![screen shot 2015-12-02 at 16 18 46](https://cloud.githubusercontent.com/assets/5332080/11524739/a7486dbc-9910-11e5-8303-d0695154a391.png)

Every time I installed Origami, and execute it, this dialog keeps showing up.

I'm sure I installed the app with the instruction of Youtube video.

I didn't do any weird thing during the installation.

platform: Mac book pro OS X El Capitan (10.11.1)

Any idea?

**Comment by suewonjp** [comment]
Origami version is 2.1.2

**Comment by suewonjp** [comment]
Well, I figured the cause.

The origami files were installed at /Library/Graphics/Quartz Composer Patches/ for unknown reasons.
( I think the files should be installed at ~/Library/Graphics/... )

So I moved the files from /Library to ~/Library and all of weird thing are gone!

My coworker didn't have this issue even though his system is almost similar to mine. (including OS version...)

Please, find the cause of why the installation process copies the files to the wrong path for your users.
I spent quite a valuable time for this issue.

**Comment by tarngerine** [comment]
Thanks for reporting this.

Could you answer an additional question: did you ever install an older version prior to 2.1.2? Did you ever install Avocado?

**Comment by suewonjp** [comment]
Neither did I.

One thing that might've been a problem was that I installed the latest beta release of Xcode before installing Origami...

After I found that Origami was not installed correctly, I replaced the beta Xcode with the stable release, but the problem was not fixed.

**Comment by tarngerine** [comment]
That should be unrelated

I may put up a faq/troubleshooting section to help with this and other common issues. Thanks!
