### ISSUE TITLE
*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]

### ISSUE THREAD

**Issue by yunshang734** [facebook/origami#59]
![qq20160103-0 2x](https://cloud.githubusercontent.com/assets/3320976/12078429/e845d7dc-b24c-11e5-9bb5-be5aab43ba55.png)
0x8b90effa: -[QCContext nextExecutionTimeForPatch:time:arguments:]
0x8b90ecb5: -[QCGraphicsContext nextExecutionTimeForPatch:time:arguments:]
0x8b90eabb: -[QCOpenGLContext nextExecutionTimeForPatch:time:arguments:]
0x8b9ca718: -[QCView nextExecutionTime:arguments:]
0x09548b5b
0x8b9ca95c: -[QCView render:arguments:]
0x8b9cb49c: -[QCView startRendering:]
0x095483f9
0x108621a1: -[FBOrigamiAdditions(Retina) startRendering:]
0x9aef667f: ___CFXRegistrationPost_block_invoke
0x9aef5d47: _CFXRegistrationPost
0x9aef5ab2: ___CFXNotificationPost_block_invoke
0x9aeefd42: -[_CFXNotificationRegistrar find:object:observer:enumerator:]
0x9adde145: _CFXNotificationPost
0x8cb8d921: -[NSNotificationCenter postNotificationName:object:userInfo:]
0x984d1a92: -[NSWindow _doWindowWillBeVisibleAsSheet:]
0x97dfecf0: -[NSWindow _reallyDoOrderWindow:relativeTo:findKey:forCounter:force:isModal:]
0x984d27e2: __71-[NSWindow _doOrderWindow:relativeTo:findKey:forCounter:force:isModal:]_block_invoke3391
0x9850a659: NSPerformVisuallyAtomicChange
0x97dfe2b2: -[NSWindow _doOrderWindow:relativeTo:findKey:forCounter:force:isModal:]
0x97dfde35: -[NSWindow orderWindow:relativeTo:]
0x97df5722: -[NSWindow makeKeyAndOrderFront:]
0x9d970ec3: -[QLSeamlessDocumentOpener showWindow:contentFrame:withBlock:]
0x97e87cf4: -[NSWindowController showWindow:]
0x09547f0d
0x09549910
0x98019632: -[NSToolbarButton sendAction:to:]
0x97f18013: -[NSToolbarItemViewer mouseDown:]
0x984cbd1d: -[NSWindow _handleMouseDownEvent:isDelayedEvent:]
0x984ccfad: -[NSWindow _reallySendEvent:isDelayedEvent:]
0x97e25735: -[NSWindow sendEvent:]
0x97e21e49: -[NSApplication sendEvent:]
0x0953f350
0x97d5503a: -[NSApplication run]

Xcode : 7.2 Quartz Composer : 4.6.1 Origami : 2.0.2

**Comment by tarngerine** [comment]
Thanks for the report. 

Can you provide steps to reproduce? Lacking a bit of context here for this crash. Does this happen frequently?

**Comment by yunshang734** [comment]
Can you speak chinese? It happens frequently when I opened a new origami file.

**Comment by tarngerine** [comment]
請給我多一點仔細的information
OS version?Have you tried reinstalling QC and origami?How frequent is frequent? Every time?Does it crash?
看起來像QC/origami在找不到摸一個檔案還是什麼。reinstall would be your best bet. 





On Sun, Jan 3, 2016 at 10:32 PM -0800, "yunshang734" <notifications@github.com> wrote:












Can you speak chinese? It happens frequently when I opened a new origami file.

**Comment by yunshang734** [comment]
I have reinstalled many times. The first step, I opened the QC; The second step, I opened a new origami file. Both of them were unresponsive. After a few minutes, this window of error message came out. The OS V of my Pro is 10.10. It happened every time. Now I have installed the newest version of origami and QC. It doesn't happen any more. I create this issue cause I think it may be an useful information for you.

**Comment by tarngerine** [comment]
Thanks for the report.
When you say you have reinstalled many times, does it work correctly for a little while and then breaks again? Please let me know if it starts happening again after this reinstall. It's not normal but I have no clue what's happening





On Tue, Jan 5, 2016 at 6:22 AM -0800, "yunshang734" <notifications@github.com> wrote:












I have reinstalled many times. The first step, I opened the QC; The second step, I opened a new origami file. Both of them were unresponsive. After a few minutes, this window of error message came out. The OS V of my Pro is 10.10. It happened every time. Now I have installed the newest version of origami and QC. It doesn't happen any more. I create this issue cause I think it may be an useful information for you.

**Comment by yunshang734** [comment]
Xcode : 7.2 Quartz Composer : 4.6.1 Origami : 2.0.2 OSV : 10.10
It happenes every time. But the newest Origami didn't happen.

**Comment by tarngerine** [comment]
Thanks. Origami 2.0.2 is out of date - please make sure you have 2.1. 






On Tue, Jan 5, 2016 at 10:59 PM -0800, "yunshang734" <notifications@github.com> wrote:












Xcode : 7.2 Quartz Composer : 4.6.1 Origami : 2.0.2 OSV : 10.10

It happenes every time. But the newest Origami didn't happen.
