### ISSUE TITLE
3d waggle export ios code

### ISSUE THREAD

**Issue by KimBin** [facebook/origami#60]
hello  i have a problem 

i download the .qtz named 3d waggle and i export the code 

in the code 

there are two  setPopAnimationProgress method and three  togglePopAnimation

1. the tow setPopAnimationProgress  method are different,but how to call it 
2. the togglePopAnimation method , two of three is the same ,but how to call it

**Comment by tarngerine** [comment]
Do you have experience developing for the platform you exported? The code export is meant to be used in conjunction with a developer who's experienced enough to take the protototype code and convert it depending on the use case. 
In this case you should probably be using a gesture recognizer's drag/move function and calculating the X/y delta and calling the functions from there. I'd consult the Paper Engineering Community on Facebook for proper engineer support - I'm limited in how I can help on this front :)






On Mon, Jan 4, 2016 at 11:36 PM -0800, "kimbin" <notifications@github.com> wrote:












hello  i have a problem 



i download the qtz named 3d waggle and i export the code 



in the code 



there are two  setPopAnimationProgress method and three  togglePopAnimation



1 the tow setPopAnimationProgress  method are different,but how to call it 

2 the togglePopAnimation method , two of three is the same ,but how to call it
