### ISSUE TITLE
Error occurred when installation finished!

### ISSUE THREAD

**Issue by Bluelich** [facebook/origami#61]
I got the 'Origami 2.1.2.pkg'  from 'http://facebook.github.io/origami/'.
But error occurred when it finished installation.
The msg is 
'Origami has been install to the wrong location(local library).Please uninstall origami using the uninstaller and reinstall from origami.facebook.com'.
What can I do to resolve it?

**Comment by tarngerine** [comment]
Have you downloaded the uninstaller that it says to download? Run the uninstaller and then try installing again. 
See this post: https://m.facebook.com/groups/508155215950032?view=permalink&id=856096031155947






On Thu, Jan 7, 2016 at 5:42 AM -0800, "Bluelich" <notifications@github.com> wrote:












I got the 'Origami 212pkg'  from 'http://facebookgithubio/origami/'

But error occurred when it finished installation

The msg is 

'Origami has been install to the wrong location(local library)Please uninstall origami using the uninstaller and reinstall from origamifacebookcom'

What can I do to resolve it?

**Comment by Bluelich** [comment]
Thank you for your help!

I'd try this(uninstall and install) several times.
But it still keep showing error.

**Comment by tarngerine** [comment]
weird. so this error pops up when the things are installed in the wrong folder. everything should be under `~/Library/Graphics`

can you run these commands in Terminal to help debug:

```
ls /Library/Graphics
ls ~/Library/Graphics
```

thanks

**Comment by Bluelich** [comment]
Thank you very much!
It seems to be solved!
The result of these two commands below:
ls /Library/Graphics :
Image Units			Quartz Composer Plug-Ins
Quartz Composer Patches

ls ~/Library/Graphics:
Quartz Composer Patches

**Comment by tarngerine** [comment]
gotcha yea. you should move everything in `/Library/Graphics` to `~/Library/Graphics`

weird permissions bug we can't reproduce :( should maybe make a top level FAQ for this

**Comment by Bluelich** [comment]
@tarngerine  
Thanks again for your help!

I move the files in  /Library/Graphics to  ~/Library/Graphics.

Now the result of 'ls /Library/Graphics' is empty.
And the result of 'ls ~/Library/Graphics' is
Image Units			Quartz Composer Plug-Ins
Quartz Composer Patches

But it seems that ,there are no files  in the  sub-path of  'Image Units' and 'Quartz Composer Plug-Ins'.
Is it right?

**Comment by Bluelich** [comment]
@tarngerine 
The system version of my Mac is 10.11.2 (15C50).

**Comment by tarngerine** [comment]
Yea idk what the Image Units folder is. If QC opens properly now you're good to go






On Mon, Jan 11, 2016 at 7:55 PM -0800, "Bluelich" <notifications@github.com> wrote:












@tarngerine 

The system version of my Mac is 10.11.2 (15C50).

**Comment by alem0lars** [comment]
I'm having the same problem.
I've installed Origami using the installer and files gets installed into `/Library/Graphics` instead of `~/Library/Graphics`

**Comment by tarngerine** [comment]
Thanks for reporting Alessandro. Could you provide some information on your computer setup：
1. What OSX version 2. Have you installed origami before3. Have you installed avocado before
Thanks






On Thu, Jan 21, 2016 at 3:50 AM -0800, "Alessandro Molari" <notifications@github.com> wrote:












I'm having the same problem.

I've installed Origami using the installer and files gets installed into /Library/Graphics instead of ~/Library/Graphics

**Comment by alem0lars** [comment]
Im using El Captain.
Ive never installed avocado.
Ive got the error the first time ive installed origami, then tried to uninstall it using the official uninstaller and then reinstalled but i still get the same error.

Alessandro Molari

**Comment by e3m** [comment]
I had same problem. After several installation/deinstallation, I'm just deinstall Origami again and remove folders Graphics in folders ~/Library and /Library/. After this I install Origami again. It's working perfectly. :) 
Hope it helps you too.
