### ISSUE TITLE
Images Exceeding Devices' boundaries in Viewer

### ISSUE THREAD

**Issue by saurabhsoni** [facebook/origami#63]
Steps Taken: 

1. Create New Project
2. Insert Image of Keyboard (750*432)
3. Changed Anchor Point to _Bottom Center_

More Info:
- Device Selected: Default - iPhone 6 - 750*1334
- Happens every time, with each project.
- Installed the latest version of Quartz, Origami and XCode as of today.

Attached Screenshot. 
<img width="1440" alt="screen shot 2016-03-17 at 12 23 45 pm" src="https://cloud.githubusercontent.com/assets/925079/13838594/1f806d66-ec3b-11e5-8c59-298bb16c12ed.png">

**Comment by saurabhsoni** [comment]
While viewing on device, iPhone 6:
- Scaling is correct, it doesn't look zoomed in. Visible width and height are 750*432
- At bottom, the keyboard image is overflowing
- If I add a header image, Anchor Point it to top left, then also scaling is correct but image overflows from device.

**Comment by bwalkin** [comment]
You need to put all of your content inside the Layer Group connected to the Viewer patch. Watch the first Origami tutorial video for more detail: http://facebook.github.io/origami/tutorials/

**Comment by saurabhsoni** [comment]
Oh, I missed this part, wasn't intuitive. Thanks @bwalkin. :)
