### ISSUE TITLE
origami.design website tutorial has a typo on the title for intended for vertical scroll views

### ISSUE THREAD

**Issue by asimpletune** [facebook/origami#73]
At the bottom of the [adding logic](https://origami.design/tutorials/common-interactions/Adding-Logic.html) page, it says 

> NEXT UP
> Scrolling Views
> Add horizontal scroll behavior to your designs.

And following [that link](https://origami.design/tutorials/common-interactions/Scrolling-Views.html) we find a title that repeats "horizontal", however this tutorial is for vertical scroll views, as the following tutorial (for carousels) is for horizontal scroll views. 

Thanks!

**Comment by tarngerine** [comment]
thanks for reporting!

**Comment by tarngerine** [comment]
PR is up and we'll be fixing it shortly. thanks!
